# On every push this script is executed
on:
  workflow_run:
    workflows: ["Minify JS/CSS on Change"]
    types:
      - completed

name: Build and deploy GH Pages
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: create CNAME dynamically
        run: echo ${CNAME} > static/CNAME
        env:
          CNAME: ${{ secrets.GH_PAGES_CNAME }}
      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@v0.20.0
        env:
          # Target branch
          PAGES_BRANCH: gh-pages
          # Provide personal access token
          #TOKEN: ${{ secrets.TOKEN }}
          # Or if publishing to the same repo, use the automatic token
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
